version: '2'
services:
    bulkemailservice-app:
        image: bulkemailservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://bulkemailservice-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=BulkEmailService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bulkemailservice-mongodb:
        extends:
            file: mongodb.yml
            service: bulkemailservice-mongodb
